[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "catala_fr_lexer"
version = "0.8"
dependencies = ["pygments"]

[project.entry-points."pygments.lexers"]
catala-fr-lexer = "catala_fr_lexer.lexer:CustomLexer"
